export const PERSON_NODE_WIDTH = 124;
export const PERSON_NODE_HEIGHT = 156;
export const RELATIONSHIP_NODE_SIZE = 28;
export const SNAP_DISTANCE = 8;
export const DAGRE_LAYOUT = {
  RANKDIR: "TB",
  NODE_SEPARATION: 72,
  RANK_SEPARATION: 96,
  PARTNER_SEPARATION: 56,
  MARGIN: 48,
};
