FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm ci

RUN npm run build:shared
RUN npm run build:web


FROM nginx:alpine

COPY --from=builder /app/apps/web/dist /usr/share/nginx/html

COPY apps/web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]