FROM node:26-alpine AS builder

WORKDIR /app

COPY package*.json ./

COPY apps/api/package*.json ./apps/api/
COPY apps/web/package*.json ./apps/web/
COPY packages/database/package*.json ./packages/database/
COPY packages/shared/package*.json ./packages/shared/

RUN --mount=type=cache,target=/root/.npm npm ci

COPY apps/web ./apps/web
COPY packages/shared ./packages/shared

RUN npm run build:shared
RUN npm run build:web


FROM nginx:alpine

COPY --from=builder /app/apps/web/dist /usr/share/nginx/html

COPY apps/web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
