version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: "/apps/api"
    target-branch: develop
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: "/apps/web"
    target-branch: develop
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 3
