services:

  web:
    image: ghcr.io/xln-0/arbora-web:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    image: ghcr.io/xln-0/arbora-api:latest
    restart: unless-stopped
    environment:
      PORT: ${PORT}

      CORS_ORIGINS: ${CORS_ORIGINS}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}

    depends_on:
      - postgres

    ports:
      - "3001:3001"


  postgres:
    image: postgres:17
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - arbora_pgdata:/var/lib/postgresql/data


volumes:
  arbora_pgdata: